---
- name: Configure IP masquerade
  yamaha_network.rtx.rtx_config:
    lines: nat descriptor type 1 masquerade
    save_when: changed

- name: Configure the pp1 interface
  yamaha_network.rtx.rtx_config:
    lines:
      - pppoe use lan2
      - pppoe auto connect on
      - pp auth accept pap chap
      - pp auth myname {{ id }} {{ password }}
      - ppp lcp mru on 1454
      - ppp ipcp ipaddress on
      - ppp ipcp msext on
      - ppp ccp type none
      - ip pp mtu 1454
      - ip pp nat descriptor 1
      - pp enable 1
    parents:
      - pp select 1
    save_when: changed

- name: Set the pp1 interface as the default gateway
  yamaha_network.rtx.rtx_config:
    lines: ip route default gateway pp 1
    save_when: changed

- name: Add DNS related settings
  yamaha_network.rtx.rtx_config:
    lines:
      - dns server pp 1
      - dns private address spoof on
    save_when: changed
